Music Library/Models/playlists.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public playlists()
        {
            this.playlists_songs = new HashSet<playlists_songs>();
        }
    
        public int id { get; set; }
        public string playlist_name { get; set; }
        public byte[] playlist_cover { get; set; }
        public int user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlists_songs> playlists_songs { get; set; }
        public virtual users users { get; set; }
    }
}

Music Library/Controllers/playlistsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Music_Library.Models;

namespace Music_Library.Controllers
{
    [Authorize]
    public class playlistsController : Controller
    {
        private Entities db = new Entities();
        private int GetAuthorizedUserId()
        {
            var user = db.users.SingleOrDefault(u => u.user_name == User.Identity.Name);
            if(user != null)
            {
                return user.id;
            }
            return -1;
        }
        public ActionResult SongList(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var songs = db.playlists;
            if (songs == null)
            {
                return HttpNotFound();
            }
            return View(songs);
        }
        // GET: playlists
        public ActionResult Index()
        {
            
             var playlists = db.playlists.ToList().Where(p => p.user_id == GetAuthorizedUserId());

            return View(playlists.ToList());
        }

        // GET: playlists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var playlists = db.playlists.ToList().Where(p => p.user_id == GetAuthorizedUserId() && p.id == id).FirstOrDefault();
            if (playlists == null)
            {
                return HttpNotFound();
            }
            return View(playlists);
        }
        public ActionResult GetImage(int id)
        {
            // fetch image data from database
            byte[] imageData = db.playlists.Find(id).playlist_cover;
            if(imageData == null)
            {
                return null;
            }


            return File(imageData, "image/jpg");
        }
        // GET: playlists/Create
        public ActionResult Create()
        {
            ViewBag.user_id = new SelectList(db.users, "id", "user_name");
            return View();
        }

        // POST: playlists/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,playlist_name,playlist_cover,user_id")] playlists playlists)
        {
            if (ModelState.IsValid)
            {
                db.playlists.Add(playlists);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.user_id = new SelectList(db.users, "id", "user_name", playlists.user_id);
            return View(playlists);
        }

        // GET: playlists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            playlists playlists = db.playlists.Find(id);
            if (playlists == null)
            {
                return HttpNotFound();
            }
            ViewBag.user_id = new SelectList(db.users, "id", "user_name", playlists.user_id);
            return View(playlists);
        }

        // POST: playlists/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,playlist_name,user_id")] playlists playlists)
        {

            HttpPostedFileBase file = Request.Files["playlist_cover"];
            
            byte[] imageBytes;
            BinaryReader reader = new BinaryReader(file.InputStream);
            imageBytes = reader.ReadBytes(file.ContentLength);
            playlists.playlist_cover = imageBytes;


            if (ModelState.IsValid)
            {
                db.Entry(playlists).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.user_id = new SelectList(db.users, "id", "user_name", playlists.user_id);
            return View(playlists);
        }

        // GET: playlists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            playlists playlists = db.playlists.Find(id);
            if (playlists == null)
            {
                return HttpNotFound();
            }
            return View(playlists);
        }

        // POST: playlists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            playlists playlists = db.playlists.Find(id);
            db.playlists.Remove(playlists);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Music Library/Views/playlists/Create.cshtml
@model Music_Library.Models.playlists

@{
    ViewBag.Title = "Добавление";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>playlists</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.playlist_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.playlist_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.playlist_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.playlist_cover, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.playlist_cover, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.playlist_cover, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_id, "user_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music Library/Views/playlists/Delete.cshtml
@model Music_Library.Models.playlists

@{
    ViewBag.Title = "Удаление";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>playlists</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Название
        </dt>

        <dd>
            @Html.DisplayFor(model => model.playlist_name)
        </dd>

        <dt>
            Обложка
        </dt>

        <dd>
            @Html.DisplayFor(model => model.playlist_cover)
        </dd>

        <dt>
            Пользователь
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users.user_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

Music Library/Views/playlists/Details.cshtml
@model Music_Library.Models.playlists

@{
    ViewBag.Title = "Детали";
}

<h2>Details</h2>

<div>
    <h4>playlists</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Название
        </dt>

        <dd>
            @Html.DisplayFor(model => model.playlist_name)
        </dd>

        <dt>
            Обложка
        </dt>

        <dd>
            @Html.DisplayFor(model => model.playlist_cover)
        </dd>

        <dt>
            Пользователь
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users.user_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

Music Library/Views/playlists/Edit.cshtml
@model Music_Library.Models.playlists

@{
    ViewBag.Title = "Редактирование";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "playlists", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>playlists</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.playlist_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.playlist_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.playlist_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.playlist_cover, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="playlist_cover" id="playlist_cover" />
                @Html.ValidationMessageFor(model => model.playlist_cover, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_id, "user_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Music Library/Views/playlists/Index.cshtml
@model IEnumerable<Music_Library.Models.playlists>

@{
    ViewBag.Title = "Список плейлистов";
}

<h2>Список плейлистов</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Название
        </th>
        <th>
            Обложка
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.playlist_name)
    </td>
    <td>
        <img style="width: 100px;height: 100px" src="@Url.Action("GetImage", new { id = item.id })" />
    </td>

    <td>
        @Html.ActionLink("Редактировать", "Edit", new { id = item.id }) |
        @Html.ActionLink("Детали", "Details", new { id = item.id }) |
        @Html.ActionLink("Удалить", "Delete", new { id = item.id })
    </td>
</tr>
}

</table>

Music Library/Views/playlists/SongList.cshtml
@model IEnumerable<Music_Library.Models.songs>


@{
    ViewBag.Title = "SongList";
}

<h2>SongList</h2>

<table class="table">
    <tr>
        <th>
            Название
        </th>
        <th>
            Автор
        </th>
        <th>
            Длительность
        </th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.song_name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.author_name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.duration)
    </td>
    <td>
        @Html.ActionLink("Редактировать", "Edit", new { id = item.id }) |
        @Html.ActionLink("Детали", "Details", new { id = item.id }) |
        @Html.ActionLink("Удалить", "Delete", new { id = item.id })
    </td>
</tr>
    }

</table>